app:
  env: UAT
  name: go-date
  port: 8080
  logFormat: text
  timeout: 60s
postgres:
  master:
    dbName: {{vault_db.master_dbname}}
    host: {{vault_db.master_host}}
    password: {{vault_db.master_password}}
    port: {{vault_db.master_port}}
    schema: {{vault_db.master_schema}}
    user: {{vault_db.master_user}}
    debug: false
  slave:
    dbName: {{vault_db.slave_dbname}}
    host: {{vault_db.slave_host}}
    password: {{vault_db.slave_password}}
    port: {{vault_db.slave_port}}
    schema: {{vault_db.slave_schema}}
    user: {{vault_db.slave_user}}
    debug: false
  maxIdleConnections: 10
  maxOpenConnections: 10
  setConMaxIdleTime: 10
  connectTimeout: 10
redis:
  host:
  db:
  password:
  failedLoginAttemptTTL: 1h
  failedLoginIssuspendTTL: 15m
  lastPageCandidateTTL: 24h
  countSwipeActionTTL: 24h
  lockingSwipeActionTTL: 1h
rateLimiter:
  maxSwipeAction: 10
  maxAttemptLogin: 3
jwtToken:
  secret: {{vault_db.jwt_secret}}
  expires: 1h