# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deployment

on: [workflow_dispatch] # trigger from button clicked

env:
  GO_VERSION: 1.20

jobs:

  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    
    steps:
    - name: Will checkout to the repo in runner
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Test
      run: go test -v ./...
    
    # - name: Build go file
    #   env:
    #     GOPATH: ${{ runner.tool_cache }}/go/${{ env.GO_VERSION }}/x64
    #     GOCACHE: ${{ secrets.HOME_DIR }}
    #   run: | 
    #     go clean --cache
    #     go build

    # - name: Deployment to Prod
    #   env: # set secret as an environment variable
    #     ANSIBLE_TEMPLATE_HOME: ${{ secrets.ANSIBLE_TEMPLATE_HOME }}
    #   run: |
    #     chmod +x ${{ github.workspace }}/push_config.sh && ${{ github.workspace }}/push_config.sh PROD ${{ github.workspace }}
